// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr3aiRsUKFuT_Dq1nRYtOU-oM2-b_UZRM',
    appId: '1:861416458459:web:d2db4e0167f4bbae8324fe',
    messagingSenderId: '861416458459',
    projectId: 'heartratemonitorproject-9355d',
    authDomain: 'heartratemonitorproject-9355d.firebaseapp.com',
    storageBucket: 'heartratemonitorproject-9355d.appspot.com',
    measurementId: 'G-ES60W7WWC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7n1q3nMzL4PIpTPy_s_iPhDwYKA4LQW8',
    appId: '1:861416458459:android:8107ba41396ecd048324fe',
    messagingSenderId: '861416458459',
    projectId: 'heartratemonitorproject-9355d',
    storageBucket: 'heartratemonitorproject-9355d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVgUU5edjOSLNt9PC-LyoDutUdZ0OYDok',
    appId: '1:861416458459:ios:5b5bba217c8ebcb18324fe',
    messagingSenderId: '861416458459',
    projectId: 'heartratemonitorproject-9355d',
    storageBucket: 'heartratemonitorproject-9355d.appspot.com',
    iosBundleId: 'com.example.heartratemonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVgUU5edjOSLNt9PC-LyoDutUdZ0OYDok',
    appId: '1:861416458459:ios:d6a64491707a90318324fe',
    messagingSenderId: '861416458459',
    projectId: 'heartratemonitorproject-9355d',
    storageBucket: 'heartratemonitorproject-9355d.appspot.com',
    iosBundleId: 'com.example.heartratemonitor.RunnerTests',
  );
}
